# Generated by Django 2.2 on 2020-01-26 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200126_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='org',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.OrgProfile'),
        ),
    ]
