# Generated by Django 2.2 on 2020-01-26 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.OrgProfile'),
        ),
    ]
