# Generated by Django 2.2 on 2020-01-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200126_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_amt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
